---
- name: "update apt"
  become: yes
  apt:
    update_cache: yes

- name: "upgrade package"
  become: yes
  apt:
    upgrade: yes

- name: "install node npm"
  become: yes
  apt:
    name: ["nodejs","npm"]
    state: latest
    update_cache: yes

- name: "install n"
  become: yes
  npm:
    name: n
    global: yes
    production: yes

- name: "install node"
  become: yes
  shell: n 13.8.0

- name: "install pm2"
  become: yes
  npm:
    name: pm2
    global: yes
    production: yes
    state: present